source ~/.dotfiles/bashrc

if [[ -f /opt/dev/dev.sh ]]; then source /opt/dev/dev.sh; fi

test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"

export PATH="$HOME/.yarn/bin:$PATH"
if [ -e /Users/rafaelfranca/.nix-profile/etc/profile.d/nix.sh ]; then . /Users/rafaelfranca/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
