# Key bindings
bindkey -e
bindkey '^p' history-search-backward
bindkey '^n' history-search-forward

# History
export HISTFILE=~/.zsh_history
export HISTSIZE=5000
export SAVEHIST=$HISTSIZE
export HISTDUP=erase
export HISTTIMEFORMAT="[%F %T] "
setopt append_history         # append history to the history file
setopt share_history          # share command history data between all sessions
setopt extended_history       # record timestamp of command in HISTFILE
setopt hist_ignore_all_dups   # don't record duplicate commands
setopt hist_save_no_dups      # don't record duplicate commands
setopt hist_ignore_dups       # don't record duplicate commands
setopt hist_find_no_dups      # don't display duplicate commands
setopt hist_ignore_space      # ignore commands that start with space
setopt hist_verify            # show command with history expansion to user before running it

export EDITOR='code --wait'

if [ $SPIN ]; then
  DOTFILES_DIR=~/dotfiles
elif [ $CODESPACES ]; then
  DOTFILES_DIR=/workspaces/.codespaces/.persistedshare/dotfiles
elif [ $REMOTE_CONTAINERS ]; then
  DOTFILES_DIR=~/dotfiles
else
  DOTFILES_DIR=~/.dotfiles
fi

# Aliases
for i in $DOTFILES_DIR/aliases/*.sh ; do . $i ; done

alias ls='ls --color'

# Load Mac-specific configurations
if [ $(uname) = "Darwin" ]; then . ~/.dotfiles/mac.sh ; fi

# Interactive prompt

autoload -Uz vcs_info
precmd_functions+=( vcs_info )
setopt prompt_subst

zstyle ':vcs_info:git:*' check-for-changes true
zstyle ':vcs_info:*' unstagedstr '*'
zstyle ':vcs_info:*' stagedstr '+'
zstyle ':vcs_info:git:*' formats '%F{200}[%b%u%c]%f'
zstyle ':vcs_info:*' enable git

PROMPT='%(?.%F{green}√.%F{red}?%?)%f [$RUBY_ENGINE-$RUBY_VERSION] %B%~%b $vcs_info_msg_0_ $ '
