# History
export HISTFILE=~/.zsh_history
export HISTSIZE=50000
export SAVEHIST=10000
export HISTTIMEFORMAT="[%F %T] "
setopt inc_append_history
setopt extended_history       # record timestamp of command in HISTFILE
setopt hist_expire_dups_first # delete duplicates first when HISTFILE size exceeds HISTSIZE
setopt hist_ignore_dups       # ignore duplicated commands history list
setopt hist_ignore_space      # ignore commands that start with space
setopt hist_verify            # show command with history expansion to user before running it
setopt share_history          # share command history data

export EDITOR='code --wait'

if [ $SPIN ]; then
  DOTFILES_DIR=~/dotfiles
elif [ $CODESPACES ]; then
  DOTFILES_DIR=/workspaces/.codespaces/.persistedshare/dotfiles
else
  DOTFILES_DIR=~/.dotfiles
fi

for i in $DOTFILES_DIR/aliases/*.sh ; do . $i ; done

# Interactive prompt

autoload -Uz vcs_info
precmd_functions+=( vcs_info )
setopt prompt_subst

zstyle ':vcs_info:git:*' check-for-changes true
zstyle ':vcs_info:*' unstagedstr '*'
zstyle ':vcs_info:*' stagedstr '+'
zstyle ':vcs_info:git:*' formats '%F{200}[%b%u%c]%f'
zstyle ':vcs_info:*' enable git

PROMPT='%(?.%F{green}√.%F{red}?%?)%f [$RUBY_ENGINE-$RUBY_VERSION] %B%~%b $vcs_info_msg_0_ $ '
