if [ $SPIN ]; then
  source /usr/local/share/chruby/chruby.sh
  source /usr/local/share/chruby/auto.sh
fi

if [ $SPIN ]; then
  DOTFILES_DIR=~/dotfiles
else
  DOTFILES_DIR=~/.dotfiles
fi

for i in $DOTFILES_DIR/aliases/*.sh ; do . $i ; done

# Interactive prompt

autoload -Uz vcs_info
precmd_functions+=( vcs_info )
setopt prompt_subst

zstyle ':vcs_info:git:*' check-for-changes true
zstyle ':vcs_info:*' unstagedstr '*'
zstyle ':vcs_info:*' stagedstr '+'
zstyle ':vcs_info:git:*' formats '%F{200}[%b%u%c]%f'
zstyle ':vcs_info:*' enable git

PROMPT='%(?.%F{green}√.%F{red}?%?)%f [$RUBY_ENGINE-$RUBY_VERSION] %B%~%b $vcs_info_msg_0_ $ '
