alias g='git status -s'
alias ungit="find . -name '.git' -exec rm -rf {} \;"
alias gb='git branch'
alias gba='git branch -a'
alias gc='git commit -v'
alias gca='git commit -v -a'
alias gco='git checkout'
alias gd='git diff'
alias gdm='git diff master'
alias gl='git pull'
alias gnp="git-notpushed"
alias gp='git push'
alias ga='git add'
alias eg="$EDITOR .git/config"
alias gr='git reset'
alias grh='git reset --hard'
alias gs='git stash'
alias gsa='git stash apply'
alias gcp='git cherry-pick'
