#!/bin/bash

if [ $SPIN ]; then
  DOTFILES_DIR=~/dotfiles
else
  DOTFILES_DIR=~/.dotfiles
fi

for i in $DOTFILES_DIR/dotfiles/*; do
  echo "Installing $(basename $i)..."
  rm -rf ~/.$(basename $i)
  ln -s $i ~/.$(basename $i)
done

if [ $SPIN ]; then
else
  git config commit.gpgsign true
fi
