#!/bin/bash

if [ $SPIN ]; then
  DOTFILES_DIR=~/dotfiles

  gpgconf --launch dirmngr
  gpg --keyserver keys.openpgp.org --recv 54FE550EA35E26D7C75362C1FC23B6D0F1EEE948
else
  DOTFILES_DIR=~/.dotfiles
fi

for i in $DOTFILES_DIR/dotfiles/*; do
  echo "Installing $(basename $i)..."
  rm -rf ~/.$(basename $i)
  ln -s $i ~/.$(basename $i)
done
