#!/bin/bash

sudo apt install -y sqlite libsqlite3-dev libpq-dev libxml2-dev libncurses-dev

sudo systemctl start redis@rails--rails
sudo systemctl start memcached@rails--rails
sudo systemctl start mysql@rails--rails

export REDIS_URL="redis://localhost:`cat /run/ports/rails--rails/svc/redis`"
export MEMCACHE_SERVERS="localhost:`cat /run/ports/rails--rails/svc/memcached`"
export MYSQL_SOCK="/var/run/mysqld-rails--rails/mysqld.sock"

mysql -uroot --socket=/var/run/mysqld-rails--rails/mysqld.sock -e "CREATE USER 'rails'@'localhost'; GRANT ALL PRIVILEGES ON activerecord_unittest.* to 'rails'@'localhost'; GRANT ALL PRIVILEGES ON activerecord_unittest2.* to 'rails'@'localhost'; GRANT ALL PRIVILEGES ON inexistent_activerecord_unittest.* to 'rails'@'localhost';"
